_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 5
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 64
data_path:
    value: data/hairNet/dataset/man_data
epochs:
    value: 50
learning_rate:
    value: 0.0005
model_save_path:
    value: checkpoints/
num_classes:
    value: 17
scheduler_gamma:
    value: 0.5
scheduler_step:
    value: 10
use_scheduler:
    value: true
use_wandb:
    value: true
weight_decay:
    value: 0.01
